### ISSUE TITLE
大佬能帮编译一个LX-R3S开发板的固件吗？我fork你的项目修改始终不成功，万分感谢！！！

### ISSUE THREAD

**Issue by kuuer** [xiaomeng9597/Actions-iStoreOS-RK33XX#1]
如题谢谢！

**Comment by xiaomeng9597** [comment]
不太好弄呢，rK3399移植istoreos要改太多东西了，还要有原始的dts设备树文件和机子才能移植和测试，本来做r08和tpm312就弄了挺久的

**Comment by kuuer** [comment]
那就不麻烦大佬了谢谢，DTS我有找到，我试着替换DTS也能开机，凑合用吧。
